CREATE DATABASE JOBS;
USE JOBS;
CREATE TABLE JOBS_DATA(
WORK_YEAR YEAR,
JOB_ROLE VARCHAR(30),
JOB_CATEGORY VARCHAR(30),
EXPERIENCE_LEVEL VARCHAR(20),
EMPLOYEMENT_TYPE VARCHAR(20),
WORK_SETTING VARCHAR(20),
COMPANY_LOCATION VARCHAR(20),
COMPANY_SIZE VARCHAR(20),
SALARY_IN_USD INT
);

-- IMPORTED TABLE DATA USING COMMAND LINE

-- Total number of jobs per year
SELECT WORK_YEAR, COUNT(*) 
FROM JOBS_DATA
GROUP BY WORK_YEAR
ORDER BY COUNT(*) DESC;   -- HIGHEST NUMBER OF JOBS WERE IN 2020 (1738), FOLLOWED BY 2021(1640), 2022(1622)
-- SINCE EVERYTHING SHIFTED TO ONLINE MODE THERE WAS MORE DEMAND IN TECH SECTOR AS MORE NUMBER OF ONLINE TOOLS WERE NEEDED.
-- IN 2021, MANY DATA EXPERTS MAY HAVE QUIT/CHANGED THEIR JOB FOR BETTER SALARY EXPECTATIONS. THEY COULDNT DO THIS IN 2020 DUE TO PANDEMIC.
-- MASSIVE HIRING WAS DONE IN 2020 DUE TO THE PANDEMIC PANIC, SO AS THE SITUATION NORMALISED, TECH COMPANIES REDUCED THEIR INTAKE AND ALSO MADE LAY OFFS.  

-- Total jobs per job role
SELECT JOB_ROLE, COUNT(*)
FROM JOBS_DATA 
GROUP BY JOB_ROLE
ORDER BY COUNT(*) DESC;   -- MORE NO. OF JOBS FOR DATA ENGG AND STATISTICIAN ROLES, LOWEST(COMPARATIVELY) FOR ML ENGG.

-- Total jobs per experience level
SELECT EXPERIENCE_LEVEL, COUNT(*)
FROM JOBS_DATA 
GROUP BY EXPERIENCE_LEVEL
ORDER BY COUNT(*) DESC;    -- MORE DEMAND FOR SENIOR LEVEL, LEAST FOR MID LEVEL.

-- Job count by work setting
SELECT WORK_SETTING, COUNT(*)
FROM JOBS_DATA 
GROUP BY WORK_SETTING
ORDER BY COUNT(*) DESC;   -- MORE DEMAND FOR HYBRID, LEAST FOR REMOTE.

-- Job count by company size
SELECT COMPANY_SIZE, COUNT(*)
FROM JOBS_DATA 
GROUP BY COMPANY_SIZE   
ORDER BY COUNT(*) DESC;   -- MORE DEMAND IN SMALL SIZED COMPANIES, LEAST IN LARGE.
-- THIS COULD BE BECAUSE LARGE COMPANIES ALREADY HAD ENOUGH PEOPLE, THEY REALISED THEY COULD WORK WITH LESSER PEOPLE
-- SMALL COMPANIES REALISED THEY CANT WORK WITHOUT PEOPLE FROM DATA FIELD,SO THEY STARTED POSTING MORE JOBS.

-- Average salary by experience level
SELECT EXPERIENCE_LEVEL, AVG(SALARY_IN_USD) 
FROM JOBS_DATA
GROUP BY EXPERIENCE_LEVEL
ORDER BY AVG(SALARY_IN_USD) DESC;
-- ENTRY LEVEL CANDIDATES HAVE HIGHEST AVG SALARY. (THIS MAY SEEM WIERD, BUT SINCE THIS DATASET IS NOT REAL DATASET AND WAS TAKEN FROM KAGGLE, IT IS POSSIBLE)
-- ANOTHER REASON THAT CAN BE IS COVID. ENTRY LEVEL FRESHERS ARE GENERALLY BETTER AT TECHNICAL LEVELS, WHICH WAS NEEDED IN THE ONLINE WORLD.   

-- Salary range (min/max) per role
SELECT JOB_ROLE, MIN(SALARY_IN_USD) AS MIN_SALARY, MAX(SALARY_IN_USD) AS MAX_SALARY, (MAX(SALARY_IN_USD)-MIN(SALARY_IN_USD)) AS SALARY_RANGE
FROM JOBS_DATA
GROUP BY JOB_ROLE
ORDER BY SALARY_RANGE DESC; 
-- WIDEST SALARY RANGE IS IN THE CASE OF DATA SCIENTISTS AND DATA ENGG, WHEREAS ITS THE LEAST IN THE CASE OF ML ENGG.  

-- Average salary by company size
SELECT COMPANY_SIZE, AVG(SALARY_IN_USD) AS AVG_SALARY
FROM JOBS_DATA
GROUP BY COMPANY_SIZE
ORDER BY AVG_SALARY DESC; 
-- AVG SALARY IS HIGHEST IN LARGE COMPANIES (THIS IS EXPECTED).
-- SECOND HIGHEST IS IN SMALL SIZE COMPANIES. THIS MAY BE BECAUSE THEY WANT TO GROW SO ARE ATTRACTING PEOPLE.  

-- Average salary by work setting
SELECT WORK_SETTING, AVG(SALARY_IN_USD) AS AVG_SALARY
FROM JOBS_DATA
GROUP BY WORK_SETTING
ORDER BY AVG_SALARY DESC;   
-- HIGHEST IN PERSON, LOWEST REMOTE.
-- THIS MAY BE BCOZ INPERSON REQUIRES MORE TIME COMMITMENT AND ALSO INCLUDES COMMUTATION COSTS.alter

-- Top 3 countries by job count
SELECT COMPANY_LOCATION, COUNT(*) AS JOB_COUNT
FROM JOBS_DATA
GROUP BY COMPANY_LOCATION
ORDER BY JOB_COUNT DESC
LIMIT 3;  
-- HIGHEST NO. OF JOBS ARE IN UK, GERMANY AND MEXICO.

-- Top 3 countries by average salary
SELECT COMPANY_LOCATION, AVG(SALARY_IN_USD) AS AVG_SALARY
FROM JOBS_DATA
GROUP BY COMPANY_LOCATION
ORDER BY AVG_SALARY DESC
LIMIT 3; 
-- JAPAN HAS HIGHEST AVG SALARY, FOLLOWED BY MEXICO AND GERMANY.

-- SO WE CAN SAY THAT IT IS BETTER TO WORK IN GERMANY, MEXICO AS THERE ARE HIGHER NO. OF JOBS AND ALSO HIGHER AVG SALARY.

-- Country-wise TOP ROLES
SELECT COMPANY_LOCATION, JOB_ROLE, COUNT(*) AS NUM_OF_ROLES
FROM JOBS_DATA T1
GROUP BY COMPANY_LOCATION, JOB_ROLE
HAVING COUNT(*) = (
    SELECT COUNT(*)
    FROM JOBS_DATA T2
    WHERE T2.COMPANY_LOCATION = T1.COMPANY_LOCATION
    GROUP BY JOB_ROLE
    ORDER BY COUNT(*) DESC
    LIMIT 1
);
-- DATA ENGGS ARE THE MOST IN DEMAND. 

-- Countries hiring most senior roles
SELECT COMPANY_LOCATION, COUNT(*) AS SENIORS
FROM JOBS_DATA
WHERE EXPERIENCE_LEVEL = 'Senior'
GROUP BY COMPANY_LOCATION
ORDER BY SENIORS DESC;
-- UK HIRES FOR MAXIMUM SENIOR ROLES, FOLLOWED BY MEXICO AND US. 
-- LEAST->JAPAN. 

-- Average salary by Role + Experience
SELECT JOB_ROLE, EXPERIENCE_LEVEL, AVG(SALARY_IN_USD) AS AVG_SALARY
FROM JOBS_DATA 
GROUP BY JOB_ROLE, EXPERIENCE_LEVEL
ORDER BY AVG_SALARY DESC;
-- MID LEVEL STATISTICIANS HAVE THE HIGHEST AVERAGE SALARY, FOLLOWED BY ML ENGG AT EXECUTIVE LEVEL, DATA SCIENTISTS AT ENTRY LEVEL.  
-- MID LEVEL ML ENGGS HAVE THE LEAST AVG SALARY.  
-- THIS MAY BE DUE TO GEOGRAPHICAL BIAS.

-- Average salary by Role + Work Setting
SELECT JOB_ROLE, WORK_SETTING, AVG(SALARY_IN_USD) AS AVG_SALARY
FROM JOBS_DATA 
GROUP BY JOB_ROLE, WORK_SETTING
ORDER BY AVG_SALARY DESC;
-- STATISTICIAN WORKING HYBRID HAVE HIGHEST AVG SALARY, FOLLOWED BY STATISTICIAN WORKING IN PERSON, ML ENGGS WORKING IN PERSON.
-- LOWEST AVG SALARY IS OF ML ENGGS WORKING REMOTE, DATA SCIENTISTS WORKING HYBRID.

-- avg Salary by Company Size + Experience
SELECT COMPANY_SIZE, EXPERIENCE_LEVEL, AVG(SALARY_IN_USD) AS AVG_SALARY
FROM JOBS_DATA
GROUP BY COMPANY_SIZE, EXPERIENCE_LEVEL
ORDER BY AVG_SALARY DESC;
-- AVERAGE SALARY IS HIGHEST FOR MEDIUM SIZED COMPANY EXECUTIVE LEVELS AND ENTRY LEVELS, FOLLOWED BY LARGE COMPANIES MID LEVEL. 
-- ITS LEAST FOR EXECUTIVE LEVEL IN SMALL SIZE COMPANIES, SENIOR LEVEL IN SMALL SIZE COMPANIES AND MID LEVEL IN MEDIUM SIZE COMPANIES.  

-- Entry-level salary comparison across countries
SELECT COMPANY_LOCATION, AVG(SALARY_IN_USD) AS AVG_SAL
FROM JOBS_DATA
WHERE EXPERIENCE_LEVEL = 'Entry-Level'
GROUP BY COMPANY_LOCATION
ORDER BY AVG_SAL DESC;
-- ENTRY LEVEL SALARIES ARE HIGHEST IN UK FOLLOWED BY INDIA, CHINA.
-- ITS LEAST IN GERMANY AND JAPAN.  

-- Best role for high salary growth
SELECT JOB_ROLE, MIN(SALARY_IN_USD) AS MIN_SAL, MAX(SALARY_IN_USD) AS MAX_SAL, (MAX(SALARY_IN_USD) - MIN(SALARY_IN_USD)) AS GROWTH
FROM JOBS_DATA
GROUP BY JOB_ROLE
ORDER BY GROWTH DESC
LIMIT 3;
-- THE BEST JOB ROLES FOR BETTER GROWTH ARE DATA SCIENTISTS, FOLLOWED BY DATA ENGINEERS, AND STATISTICIANS.

-- Best country for remote high-pay roles
SELECT COMPANY_LOCATION, AVG(SALARY_IN_USD) AS AVG_SAL
FROM JOBS_DATA
WHERE WORK_SETTING = 'Remote'
GROUP BY COMPANY_LOCATION
ORDER BY AVG_SAL DESC
LIMIT 3;
-- CHINA, US, GERMANY





